name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:name: CI

on: 
  push:
    branches:
      - development
  pull_request:
  workflow_call:
    inputs:
      repository:
        default: desktop/desktop
        required: false
        type: string
      ref:
        required: true
        type: string
      upload-artifacts:
        default: false
        required: false
        type: boolean
      environment:
        type: string
        required: true
    secrets:
      DESKTOP_OAUTH_CLIENT_ID:
      DESKTOP_OAUTH_CLIENT_SECRET:
      APPLE_ID:
      APPLE_ID_PASSWORD:
      APPLE_APPLICATION_CERT:
      APPLE_APPLICATION_CERT_PASSWORD:
      WINDOWS_CERT_PFX:
      WINDOWS_CERT_PASSWORD:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository || github.repository }}
    types: [github.com/farahmandakbar26/desktop/development/.github/workflows/no-response.yml]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

permissions:
  issues: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          closeComment: >
            Thank you for your issue!

            We haven’t gotten a response to our questions above. With only the
            information that is currently in the issue, we don’t have enough
            information to take action. We’re going to close this but don’t
            hesitate to reach out if you have or find the answers we need. If
            you answer our questions above, this issue will automatically
            reopen.
          daysUntilClose: 7
          responseRequiredLabel: more-info-needed
